services:
  - type: web
    name: dana-mutasi-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: SHEET_ID
        sync: false
      - key: REDIS_URL
        sync: false
      - key: GOOGLE_CREDS_JSON
        sync: false
    healthCheckPath: /health
    autoDeploy: true